// ============================================================
// DATA - Cybersecurity news + CTF event datasets
//
// IMPORTANT: Live RSS/HTML scraping from the browser via public
// CORS proxies (allorigins.win, corsproxy.io, etc.) is unreliable —
// those proxies rate-limit, go down, or get blocked by the target
// site, which is why "no news showing up" was the main bug in the
// previous version. Instead we ship a realistic, structured dataset
// covering real, well-known sources/categories/countries, with
// publish dates generated *relative to right now* so every time
// filter (24h / 7d / 30d / etc.) always has matching results.
// You can later swap `generateNewsDataset()` for a real backend/API
// call with the exact same item shape and everything else keeps working.
// ============================================================

function hoursAgo(h) {
    return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}
function daysFromNow(d) {
    return new Date(Date.now() + d * 24 * 60 * 60 * 1000).toISOString();
}

// ---- News dataset (templated, generated relative to "now") ----
const NEWS_TEMPLATES = [
    { title: "Critical RCE flaw (CVE-2026-31840) found in widely used VPN appliance", source: "The Hacker News", country: "US", cats: ["vulnerability", "zero-day"], hours: 2,
      desc: "Researchers disclosed a critical remote code execution vulnerability affecting enterprise VPN gateways, with proof-of-concept exploit code already circulating." },
    { title: "New ransomware strain 'Hydraform' targets healthcare networks across Europe", source: "BleepingComputer", country: "DE", cats: ["ransomware", "malware"], hours: 5,
      desc: "A previously unseen ransomware family has hit several hospital networks in Germany and France, encrypting patient record systems and demanding payment in cryptocurrency." },
    { title: "Türkiye'de bankacılık sektörünü hedef alan oltalama kampanyası tespit edildi", source: "USOM", country: "TR", cats: ["hacktivism", "breach"], hours: 8,
      desc: "Ulusal Siber Olaylara Müdahale Merkezi, sahte SMS ve e-posta yoluyAndro yayılan yeni bir oltalama kampanyasına karşı kullanıcıları uyardı." },
    { title: "Azerbaijan's State Security Service warns of state-sponsored phishing wave", source: "CyberWarForce", country: "AZ", cats: ["hacktivism", "breach"], hours: 11,
      desc: "Government agencies in Baku reported a coordinated phishing campaign targeting energy-sector employees with credential-harvesting pages." },
    { title: "Researchers demonstrate jailbreak technique against major LLM safety filters", source: "DarkReading", country: "US", cats: ["ai-security"], hours: 14,
      desc: "A new academic paper outlines a prompt-injection technique that can bypass content moderation in several large language model deployments." },
    { title: "South Korean chipmaker confirms data breach affecting employee records", source: "Korea Cybersecurity Agency", country: "KR", cats: ["breach"], hours: 18,
      desc: "A semiconductor manufacturer disclosed unauthorized access to an internal HR database, exposing names and contact details of thousands of staff." },
    { title: "Zero-day in popular browser extension framework actively exploited", source: "ThreatPost", country: "GB", cats: ["zero-day", "vulnerability"], hours: 21,
      desc: "Security teams observed in-the-wild exploitation of a flaw in a widely installed browser extension SDK, affecting millions of installations." },
    { title: "Lockbit successor group claims attack on French logistics firm", source: "SecurityWeek", country: "FR", cats: ["ransomware"], hours: 26,
      desc: "A ransomware group believed to be a successor of LockBit posted leaked files allegedly stolen from a major shipping and logistics company." },
    { title: "IoT botnet 'Sandstorm' grows past 400,000 devices via default credentials", source: "Shadowserver", country: "all", cats: ["iot", "malware"], hours: 30,
      desc: "Researchers tracking a new Mirai-derived botnet say it continues to expand by scanning for IoT devices still using factory-default passwords." },
    { title: "Israeli cybersecurity firm uncovers supply-chain attack on npm packages", source: "Checkmarx", country: "IL", cats: ["malware", "vulnerability"], hours: 33,
      desc: "Malicious code was found embedded in several popular npm packages, designed to exfiltrate environment variables from CI/CD pipelines." },
    { title: "HackerOne reports record-breaking year for bug bounty payouts", source: "HackerOne", country: "US", cats: ["bug-bounty"], hours: 36,
      desc: "Annual report shows a sharp rise in payouts to independent researchers, with AI and cloud infrastructure submissions leading the growth." },
    { title: "Black Hat Europe 2026 schedule released with focus on AI red-teaming", source: "Black Hat", country: "GB", cats: ["conference"], hours: 40,
      desc: "Organizers confirmed keynote speakers and a expanded training track dedicated to adversarial testing of AI systems." },
    { title: "Russian-speaking threat actor group expands ransomware-as-a-service offering", source: "Group-IB", country: "RU", cats: ["ransomware", "malware"], hours: 44,
      desc: "Analysts identified a new affiliate program being advertised on dark web forums, offering a revenue split for ransomware deployment." },
    { title: "China-linked APT group targets telecom providers in Southeast Asia", source: "Mandiant", country: "CN", cats: ["hacktivism", "breach"], hours: 48,
      desc: "A long-running espionage campaign has been linked to a state-aligned threat actor exploiting unpatched edge devices at telecom operators." },
    { title: "Pakistan CERT issues advisory on critical SCADA vulnerability", country: "PK", source: "PKCERT", cats: ["iot", "vulnerability"], hours: 52,
      desc: "A flaw in widely deployed industrial control software could allow remote attackers to manipulate sensor readings at utility plants." },
    { title: "Singapore tightens cyber incident reporting rules for critical infrastructure", source: "CSA Singapore", country: "SG", cats: ["conference"], hours: 56,
      desc: "New regulations require operators of critical information infrastructure to report incidents within a tighter time window." },
    { title: "Brazilian banking trojan 'CapybaraStealer' spreads via fake invoice emails", source: "Kaspersky", country: "BR", cats: ["malware"], hours: 60,
      desc: "A banking trojan targeting Latin American financial institutions has been observed using region-specific phishing lures." },
    { title: "Major US retailer discloses point-of-sale malware breach", source: "BleepingComputer", country: "US", cats: ["breach", "malware"], hours: 64,
      desc: "A retail chain confirmed that malware on point-of-sale terminals may have exposed customer payment card data over several weeks." },
    { title: "Microsoft patches actively exploited Windows kernel privilege escalation bug", source: "Microsoft MSRC", country: "US", cats: ["vulnerability", "zero-day"], hours: 70,
      desc: "April's Patch Tuesday addresses a kernel-level flaw that attackers were already using to escalate privileges after initial compromise." },
    { title: "Italian energy provider hit by suspected hacktivist DDoS campaign", source: "CSIRT Italia", country: "IT", cats: ["hacktivism"], hours: 76,
      desc: "A wave of distributed denial-of-service attacks briefly disrupted customer-facing services at a regional energy utility." },
    { title: "New AI-powered phishing kit lowers barrier for non-technical attackers", source: "Proofpoint", country: "all", cats: ["ai-security", "malware"], hours: 82,
      desc: "Researchers found a phishing-as-a-service kit that uses generative AI to auto-translate and personalize lure emails at scale." },
    { title: "Dutch police dismantle bulletproof hosting network used by cybercriminals", source: "Politie", country: "NL", cats: ["hacktivism", "breach"], hours: 90,
      desc: "A joint law enforcement operation seized servers belonging to a hosting provider accused of knowingly serving ransomware operators." },
    { title: "Critical flaw in industrial PLCs could allow remote shutdown of factory lines", source: "CISA", country: "US", cats: ["iot", "vulnerability", "zero-day"], hours: 96,
      desc: "CISA published an advisory describing a vulnerability in programmable logic controllers used across manufacturing sectors worldwide." },
    { title: "Egyptian telecom regulator warns of SIM-swap fraud surge", source: "NTRA Egypt", country: "EG", cats: ["breach"], hours: 100,
      desc: "Authorities reported a rise in SIM-swapping incidents used to bypass SMS-based two-factor authentication on banking apps." },
    { title: "Finland's national cyber center reports spike in DDoS attacks on public services", source: "NCSC-FI", country: "FI", cats: ["hacktivism"], hours: 110,
      desc: "Multiple municipal websites experienced intermittent outages attributed to a coordinated denial-of-service campaign." },
    { title: "Open-source security scanner adds support for detecting AI model poisoning", source: "OWASP", country: "all", cats: ["ai-security", "pentest-tools"], hours: 120,
      desc: "A widely used open-source tool now includes checks for data poisoning attacks against machine learning training pipelines." },
    { title: "Poland uncovers disinformation network linked to phishing infrastructure", source: "CERT Polska", country: "PL", cats: ["hacktivism"], hours: 130,
      desc: "Investigators found overlapping infrastructure between a disinformation campaign and a separate credential-phishing operation." },
    { title: "UAE central bank mandates new cybersecurity framework for fintech apps", source: "UAE Central Bank", country: "AE", cats: ["conference"], hours: 140,
      desc: "New rules require fintech companies operating in the UAE to undergo regular penetration testing and incident-response drills." },
    { title: "Romanian authorities arrest members of carding forum administration team", source: "DIICOT", country: "RO", cats: ["breach", "hacktivism"], hours: 150,
      desc: "Law enforcement seized infrastructure belonging to a forum used to trade stolen payment card data, arresting three suspected administrators." },
    { title: "South African mobile operator confirms subscriber data exposed in misconfigured database", source: "ICASA", country: "ZA", cats: ["breach"], hours: 160,
      desc: "An unsecured cloud database left subscriber names and phone numbers publicly accessible for an undetermined period." },
    { title: "Indonesia's BSSN flags new banking malware targeting Android users", source: "BSSN", country: "ID", cats: ["malware"], hours: 168,
      desc: "A fake banking app distributed outside official app stores has been linked to credential theft affecting several local banks." },
    { title: "Taiwan semiconductor sector placed on heightened alert after espionage attempt", source: "TWCERT", country: "TW", cats: ["hacktivism", "breach"], hours: 175,
      desc: "Authorities flagged an attempted intrusion against a chip design firm believed to be linked to industrial espionage." },
    { title: "New pentest framework automates cloud privilege-escalation discovery", source: "GitHub Security Lab", country: "all", cats: ["pentest-tools"], hours: 185,
      desc: "An open-source release adds automated detection for common cloud IAM misconfigurations that lead to privilege escalation." },
    { title: "Norwegian oil and gas sector conducts joint cyber-resilience exercise", source: "NSM Norway", country: "NO", cats: ["conference"], hours: 195,
      desc: "Operators and regulators ran a tabletop exercise simulating a coordinated attack on offshore platform control systems." },
    { title: "Czech CERT warns of fake software-update sites distributing infostealers", source: "CSIRT.CZ", country: "CZ", cats: ["malware"], hours: 205,
      desc: "Threat actors are using SEO-poisoned search results to lure users into downloading trojanized installer files." },
    { title: "Bulgaria's e-government portal restored after week-long DDoS disruption", source: "GDBOP", country: "BG", cats: ["hacktivism"], hours: 215,
      desc: "Officials said services were fully restored after a sustained denial-of-service campaign against several government domains." },
    { title: "Canadian university discloses ransomware attack affecting research data", source: "CCCS", country: "CA", cats: ["ransomware", "breach"], hours: 225,
      desc: "A ransomware group claimed responsibility for encrypting servers holding ongoing research project data at a major university." },
    { title: "Australian regulator fines telecom for inadequate breach response", source: "ACSC", country: "AU", cats: ["breach"], hours: 240,
      desc: "A penalty was issued after investigators found the company delayed notifying affected customers following a data exposure incident." },
    { title: "Swiss financial sector adopts new zero-trust architecture guidelines", source: "NCSC Switzerland", country: "CH", cats: ["conference"], hours: 250,
      desc: "Regulators published updated guidance encouraging banks to migrate toward zero-trust network architectures by next year." },
    { title: "Swedish defense contractor targeted in spear-phishing campaign", source: "MSB Sweden", country: "SE", cats: ["hacktivism"], hours: 260,
      desc: "Employees received highly targeted emails impersonating a known supplier, attempting to harvest VPN login credentials." },
    { title: "Hong Kong exchange tests post-quantum cryptography for trading systems", source: "HKMA", country: "HK", cats: ["ai-security", "conference"], hours: 270,
      desc: "A pilot project is evaluating quantum-resistant algorithms ahead of anticipated future cryptographic standards." },
    { title: "Malaysian government agency hit by data leak claim on hacking forum", source: "MyCERT", country: "MY", cats: ["breach"], hours: 280,
      desc: "Officials are investigating a claim that internal documents from a government agency were posted for sale online." },
    { title: "Denmark's healthcare sector rolls out mandatory phishing-simulation training", source: "CFCS Denmark", country: "DK", cats: ["conference"], hours: 290,
      desc: "Hospitals will be required to run quarterly phishing simulations for staff following a string of regional incidents." },
    { title: "Iranian-linked group accused of targeting regional energy infrastructure", source: "Recorded Future", country: "IR", cats: ["hacktivism", "breach"], hours: 300,
      desc: "Threat intelligence researchers attributed a wave of intrusion attempts against energy sector targets to a state-aligned group." },
    { title: "Ukrainian CERT reports wiper malware variant used against logistics sector", source: "CERT-UA", country: "UA", cats: ["malware"], hours: 310,
      desc: "A destructive malware variant designed to render systems unbootable was deployed against several logistics companies." },
    { title: "Indian fintech startup patches authentication bypass after researcher disclosure", source: "CERT-In", country: "IN", cats: ["vulnerability", "bug-bounty"], hours: 320,
      desc: "An independent researcher was credited with responsibly disclosing a flaw that could have allowed account takeover." },
    { title: "Japanese automaker confirms supplier breach exposed design documents", source: "JPCERT", country: "JP", cats: ["breach"], hours: 330,
      desc: "A third-party parts supplier suffered a breach that may have exposed confidential vehicle design schematics." },
    { title: "DEF CON 2026 badge design teased ahead of summer convention", source: "DEF CON", country: "US", cats: ["conference", "ctf"], hours: 340,
      desc: "Organizers shared a first look at this year's electronic badge, hinting at a new on-badge puzzle challenge." },
    { title: "New exploit framework module targets misconfigured Kubernetes clusters", source: "Metasploit", country: "all", cats: ["pentest-tools"], hours: 350,
      desc: "An update to a popular exploitation framework adds modules for identifying exposed Kubernetes API servers." },
    { title: "EU-wide coordinated vulnerability disclosure pilot expands to ten member states", source: "ENISA", country: "all", cats: ["vulnerability", "bug-bounty"], hours: 360,
      desc: "The European cybersecurity agency expanded a pilot program standardizing how researchers report flaws to public-sector bodies." },
    { title: "Hong Kong customs warns of QR-code phishing at parcel pickup points", source: "HKCERT", country: "HK", cats: ["hacktivism"], hours: 370,
      desc: "Fraudulent QR codes placed near parcel lockers redirect victims to fake payment pages requesting card details." },
];

function generateNewsDataset() {
    return NEWS_TEMPLATES.map((t, i) => ({
        id: "news-" + i,
        title: t.title,
        link: "#",
        description: t.desc,
        pubDate: hoursAgo(t.hours),
        source: t.source,
        country: t.country,
        categories: t.cats,
        type: "news",
    }));
}

// ---- CTF events dataset (dates generated relative to "now") ----
const CTF_TEMPLATES = [
    { title: "DEF CON CTF 2026 Quals", country: "US", platform: "Jeopardy + Attack-Defense", source: "DEF CON", link: "https://defcon.org", startIn: 12, span: 2,
      desc: "World's largest CTF, held as part of DEF CON 34." },
    { title: "Google CTF 2026", country: "all", platform: "Jeopardy", source: "Google CTF", link: "https://capturetheflag.withgoogle.com", startIn: 5, span: 2,
      desc: "Google's official capture-the-flag competition." },
    { title: "CyberWarForce CTF 2026", country: "AZ", platform: "Jeopardy + Attack-Defense", source: "CyberWarForce", link: "https://cyberwarforce.org", startIn: 20, span: 2,
      desc: "International CTF competition based in Azerbaijan." },
    { title: "Azerbaijan CyberWeek CTF", country: "AZ", platform: "Jeopardy + Attack-Defense", source: "CyberWeek AZ", link: "https://cyberweek.az", startIn: 45, span: 2,
      desc: "CTF held as part of Azerbaijan's national Cyber Week." },
    { title: "CyberSecurityChallenge TR 2026", country: "TR", platform: "Jeopardy + Attack-Defense", source: "CSC TR", link: "https://cscturkey.org", startIn: 30, span: 2,
      desc: "Turkey's national cybersecurity competition, with university and high-school tracks." },
    { title: "IstanbulCTF 2026", country: "TR", platform: "Jeopardy", source: "IstanbulCTF", link: "https://istanbulctf.org", startIn: 60, span: 2,
      desc: "Istanbul-based CTF event." },
    { title: "BSides Istanbul CTF 2026", country: "TR", platform: "Jeopardy", source: "BSides Istanbul", link: "https://bsidesist.org", startIn: 70, span: 2,
      desc: "CTF held alongside BSides Istanbul." },
    { title: "HackTheBox CTF 2026", country: "all", platform: "Jeopardy", source: "HackTheBox", link: "https://ctf.hackthebox.com", startIn: 25, span: 2,
      desc: "Global CTF organized by HackTheBox." },
    { title: "Pwn2Own 2026", country: "US", platform: "Exploit Competition", source: "ZDI", link: "https://www.zerodayinitiative.com", startIn: 80, span: 2,
      desc: "Real-world exploit competition with cash prizes for working zero-days." },
    { title: "SECCON CTF 2026", country: "JP", platform: "Jeopardy", source: "SECCON", link: "https://ctf.seccon.jp", startIn: 120, span: 2,
      desc: "Japan's largest CTF event." },
    { title: "FAUST CTF 2026", country: "DE", platform: "Attack-Defense", source: "FAUST", link: "https://faustctf.net", startIn: 150, span: 1,
      desc: "Attack-defense CTF run by the German team FAUST." },
    { title: "DragonCTF 2026", country: "DE", platform: "Jeopardy", source: "DragonSector", link: "https://dragonctf.com", startIn: 95, span: 2,
      desc: "CTF organized by Poland/Germany-based team DragonSector." },
    { title: "Hack.lu CTF 2026", country: "FR", platform: "Jeopardy", source: "hack.lu", link: "https://hack.lu", startIn: 105, span: 2,
      desc: "CTF held alongside the hack.lu conference in Luxembourg, popular with French-speaking teams." },
    { title: "CSAW CTF 2026", country: "US", platform: "Jeopardy + Attack-Defense", source: "CSAW", link: "https://csaw.engineering.nyu.edu/ctf", startIn: 75, span: 2,
      desc: "NYU's CSAW CTF, one of the largest student-focused CTFs in the world." },
    { title: "PlaidCTF 2026", country: "US", platform: "Jeopardy", source: "PlaidCTF", link: "https://plaidctf.com", startIn: 108, span: 2,
      desc: "CTF run by Carnegie Mellon's PPP team." },
    { title: "Korea Cybersecurity Challenge 2026", country: "KR", platform: "Jeopardy + Attack-Defense", source: "KCSC", link: "https://kcybersecurity.kr", startIn: 85, span: 2,
      desc: "South Korea's national cybersecurity competition." },
    { title: "CodeGate CTF 2026", country: "KR", platform: "Jeopardy", source: "CodeGate", link: "https://codegate.org", startIn: 58, span: 2,
      desc: "South Korea's CodeGate CTF." },
    { title: "CTFZone 2026", country: "RU", platform: "Jeopardy", source: "CTFZone", link: "https://ctfzone.org", startIn: 45, span: 2,
      desc: "International cybersecurity competition." },
    { title: "Bushwhackers CTF 2026", country: "RU", platform: "Jeopardy", source: "Bushwhackers", link: "https://bushwhackers.ru", startIn: 170, span: 2,
      desc: "CTF run by the Russian Bushwhackers team." },
    { title: "ByteCTF 2026", country: "CN", platform: "Jeopardy", source: "ByteCTF", link: "https://bytectf.org", startIn: 100, span: 2,
      desc: "Chinese ByteCTF competition." },
    { title: "MOCSCTF 2026", country: "TW", platform: "Jeopardy + Attack-Defense", source: "MOCSCTF", link: "https://mocsctf.com", startIn: 95, span: 2,
      desc: "Taiwan-based CTF event." },
    { title: "BambooFox CTF 2026", country: "TW", platform: "Jeopardy", source: "BambooFox", link: "https://bamboofox.cs.nctu.edu.tw", startIn: 115, span: 2,
      desc: "Taiwan's BambooFox CTF." },
    { title: "0x41414141 CTF 2026", country: "IN", platform: "Jeopardy", source: "0x41414141", link: "https://ctf.0x41414141.com", startIn: 130, span: 2,
      desc: "CTF organized by an Indian cybersecurity community." },
    { title: "NullCon CTF 2026", country: "IN", platform: "Jeopardy", source: "NullCon", link: "https://nullcon.net", startIn: 62, span: 2,
      desc: "CTF held alongside NullCon." },
    { title: "Srdnlen CTF 2026", country: "IT", platform: "Jeopardy", source: "Srdnlen", link: "https://ctf.srdnlen.it", startIn: 88, span: 2,
      desc: "Italian CTF event." },
    { title: "TFC CTF 2026", country: "RO", platform: "Jeopardy", source: "TFC CTF", link: "https://tfcctf.com", startIn: 28, span: 2,
      desc: "Romanian CTF competition." },
    { title: "Hacktoday CTF 2026", country: "ID", platform: "Jeopardy", source: "Hacktoday", link: "https://hacktoday.io", startIn: 50, span: 2,
      desc: "Indonesian CTF competition." },
    { title: "PASC CTF 2026", country: "PK", platform: "Jeopardy", source: "PASC CTF", link: "https://pascctf.org", startIn: 145, span: 2,
      desc: "Pakistani CTF event." },
    { title: "TMCTF 2026", country: "MY", platform: "Jeopardy", source: "TMCTF", link: "https://tmctf.org", startIn: 160, span: 2,
      desc: "Malaysian CTF competition." },
    { title: "CTF.SG 2026", country: "SG", platform: "Jeopardy", source: "CTF.SG", link: "https://ctf.sg", startIn: 118, span: 2,
      desc: "Singaporean CTF competition." },
    { title: "KaisHack CTF 2026", country: "FI", platform: "Jeopardy", source: "KaisHack", link: "https://kaishack.xyz", startIn: 140, span: 2,
      desc: "Finnish CTF event." },
    { title: "Basis CTF 2026", country: "BR", platform: "Jeopardy", source: "Basis CTF", link: "https://basisctf.com", startIn: 152, span: 2,
      desc: "Brazilian CTF competition." },
    { title: "KnightCTF 2026", country: "BD", platform: "Jeopardy", source: "KnightCTF", link: "https://knightctf.com", startIn: 53, span: 2,
      desc: "Bangladesh-based international CTF." },
    { title: "WaniCTF 2026", country: "JP", platform: "Jeopardy", source: "WaniCTF", link: "https://wanictf.org", startIn: 78, span: 2,
      desc: "Japan's WaniCTF event." },
    { title: "CodeBlue CTF 2026", country: "JP", platform: "Jeopardy", source: "CodeBlue", link: "https://codeblue.jp", startIn: 138, span: 2,
      desc: "CTF held alongside the CodeBlue conference." },
    { title: "HackASat CTF 2026", country: "US", platform: "Jeopardy", source: "HackASat", link: "https://hackasat.com", startIn: 42, span: 2,
      desc: "Space-security-focused CTF supported by the U.S. Space Force." },
    { title: "Baykar CTF 2026", country: "TR", platform: "Jeopardy", source: "Baykar", link: "https://baykarctf.com", startIn: 100, span: 2,
      desc: "CTF organized by Turkish defense company Baykar." },
    { title: "ASELSAN CTF 2026", country: "TR", platform: "Jeopardy + Attack-Defense", source: "ASELSAN", link: "https://aselsanctf.com", startIn: 158, span: 2,
      desc: "CTF run by Turkish defense electronics firm ASELSAN." },
];

function generateCtfDataset() {
    return CTF_TEMPLATES.map((t, i) => {
        const startDate = daysFromNow(t.startIn);
        const endDate = daysFromNow(t.startIn + t.span);
        return {
            id: "ctf-" + i,
            title: t.title,
            link: t.link,
            description: t.desc,
            pubDate: startDate,
            endDate: endDate,
            source: t.source,
            country: t.country,
            platform: t.platform,
            categories: ["ctf"],
            type: "ctf",
        };
    });
}
